### ISSUE TITLE
ライブラリの間違い

### ISSUE THREAD

**Issue by NaotakaSaito** [SWITCHSCIENCE/BME280#2]
以下のファイルの、readTrim()関数のdig_H5とdig_H6の設定は間違っているのではないでしょうか？
ご確認ください。

BME280/Arduino/libraries/SSCI_BME280/SSCI_BME280.cpp

現状：
void SSCI_BME280::readTrim()
{
  calibData.dig_H5 = (data[31] << 4) | ((data[30] >> 4) & 0x0F);
  calibData.dig_H6 = data[32];
}

修正案：
void SSCI_BME280::readTrim()
{
  calibData.dig_H5 = (data[30] << 4) | ((data[29] >> 4) & 0x0F);
  calibData.dig_H6 = data[31];
}

**Comment by Shinichi-Ohki** [comment]
ご指摘ありがとうございます。確かに間違っていましたので修正しました。
